### ISSUE TITLE
"Extension" is spelled wrong

### ISSUE THREAD

**Issue by macalinao** [sangria-graphql/sangria-slowlog#1]
Sorry about my OCD, but the code says "extention" when it's actually spelled "extension."

https://forum.wordreference.com/threads/extension-vs-extention.3040710/

This would be a breaking change, so I didn't make a PR for this. Please let me know if you'd be fine with me fixing it :)

**Comment by OlegIlyenko** [comment]
OMG... I knew that this typo will slip somewhere :) Looks like only `addExtentions` is affected. I would appreciate if could make a PR with the fix. It is indeed a breaking change, but pretty minor one and should be easy to resolve. I think it should be ok, especially if we mention it in the release notes.

**Comment by macalinao** [comment]
Ok, will send a PR your way shortly :)

**Comment by OlegIlyenko** [comment]
Fixed in #2
